## Introduction
### Background

Rural-urban labour migration is a critical driver of economic development in Ghana. The structural transformation agenda by the government of Ghana influences urbanization patterns, labour market dynamics, and rural livelihoods. However, traditional data collection methods, such as surveys and censuses, often fail to capture the fluid and dynamic nature of migration. In this context, Call Detail Records (CDR) from mobile phone networks present a novel, cost-effective, and scalable approach to understanding migration trends.

CDR data provide a rich source of information on the movement patterns of individuals, derived from their interactions with mobile phone towers. By leveraging CDR data, this project seeks to generate actionable insights into the volume, direction, and frequency of rural-urban labour migration in Ghana, with a focus on identifying patterns, trends, and socio-economic implications.


### Purpose

In this project, Ghana Statistical Service and Flowminder in collaborating with the ONS Accelerator Program to develop data science solutions which may improved our understanding of labour movement with the use of dynamic population estimates. Many public metrics and indicators on migration are calculated using the traditional data sources most often used to estimate population size, such as censuses or surveys, often cannot account for seasonal variations and migration trends, and therefore may be inaccurate and outdated.

This document, presents monthly, district-level population estimates from CDR data provided by Telecel Ghana, and other datasets to provide actionable insights on labour movement. We also present our main findings on the variations in the district-level population between Rural and Urban zones as a response to government policies.